source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CYFCalendarView_Example', :exclusive => true do
  pod "CYFCalendarView", :path => "../"
end

target 'CYFCalendarView_Tests', :exclusive => true do
  pod "CYFCalendarView", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
